repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.34.1
    hooks:
      - id: golangci-lint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy